/**
 * 
 * Controller class that instantiates a new DoOCR object on the current image file and processes the 
 *  output generated by Tesseract
 *
 * This class currently is designed with regex that only works with labs received from Quest VA
 * In order to enable other lab sources, code here (particularly regex functions) will need to
 * 	be refactored in addition to the creation of subclasses for each lab source
 * 
 * Controller class to LabDocData, invoking that class when data is matched via regex and storing it in a HashMap
 * LabDocData objects are thereafter mapped to their parent LabDocSection classes, which are instantiated upon
 *  identification of a LabDocData object child to them
 *
 * Eventually, this class will be refactored into component regex classes.
 *
 */

package labBot;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Scanner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public abstract class LabDocScanner {

	protected ArrayList<String> ocrResults = new ArrayList<String>();
	protected ArrayList<String> matchResults = new ArrayList<String>();
	public String firstName, lastName, dataSourceType;
	public static final File source = new File("E:/CHSEE/QUESTVA_fake_AgAb.txt");
	protected static HashMap<String,LabDocData> dataInDoc = new HashMap<String,LabDocData>();
	protected static HashMap<String,LabDocSection> sectionsInDoc = new HashMap<String,LabDocSection>();
 	
	public LabDocScanner() {
		try {
			Scanner fileReader = new Scanner(source);
			while (fileReader.hasNext()) {
				ocrResults.add(fileReader.nextLine());
			}
			fileReader.close();
		} catch (FileNotFoundException e) {
			System.out.println("File not found!");
		}
	}

	protected boolean doRegex(String line, String pattern) {
		Pattern name = Pattern.compile(pattern);
		Matcher matches = name.matcher(line);
		//System.out.println(line);
		matchResults.clear();
		if (matches.find()) {
			for (int i=1; i<=matches.groupCount(); i++) {
					matchResults.add(matches.group(i));
			}
			return true;
		} else {
			return false;
		}	
	}
	
	public LabDocData getDataFromHashMap(String dataSourceType) {
		return dataInDoc.get(dataSourceType);
	}
	
	public String getValue(LabDocScanner scanner, String dataSourceType) {
		return scanner.getDataFromHashMap(dataSourceType).getDataValue();
	}
	
	public String getFieldId(LabDocScanner scanner, String dataSourceType) {
		return scanner.getDataFromHashMap(dataSourceType).getDataFieldHtmlId();
	}
	
	protected LabDocSection getLabDocSectionByName(String name) {
		return sectionsInDoc.get(name);
	}
	
	protected abstract void setLabName();
	
}
